name: spare_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.0.4
  flutter_lints: ^3.0.0
  get: ^4.6.5
  intl: ^0.18.1
  country_code_picker: ^3.0.0
  get_storage: ^2.1.1
  image_picker: ^1.0.5
  permission_handler: ^11.0.0
  device_info_plus: ^9.1.0
  flutter_image_compress: ^2.1.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  animated_notch_bottom_bar: ^1.0.3
  carousel_slider: ^4.0.0
  local_auth: ^2.1.7
  firebase_database: ^10.0.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.1
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.6.0
  http: ^1.2.2
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Ensure your logo is in this directory

flutter_native_splash:
  color: "#E0342F"  # Set your desired background color here
  image: assets/images/logo.png  # Path to your logo
  android: true
  ios: true
  web: false
